-- MySQL Script generated by MySQL Workbench
-- Wed Mar 27 10:24:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema footwearPortal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema footwearPortal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `footwearPortal` DEFAULT CHARACTER SET utf8 ;
USE `footwearPortal` ;

-- -----------------------------------------------------
-- Table `footwearPortal`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footwearPortal`.`user` (
  `UID` VARCHAR(8) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `group` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`UID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footwearPortal`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footwearPortal`.`company` (
  `companyID` VARCHAR(8) NOT NULL,
  `companyName` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`companyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footwearPortal`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footwearPortal`.`supervisor` (
  `UID` VARCHAR(8) NOT NULL,
  `companyID` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`UID`, `companyID`),
  INDEX `fk_supervisor_company_idx` (`companyID` ASC),
  INDEX `fk_supervisor_user1_idx` (`UID` ASC),
  CONSTRAINT `fk_supervisor_company`
    FOREIGN KEY (`companyID`)
    REFERENCES `footwearPortal`.`company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supervisor_user1`
    FOREIGN KEY (`UID`)
    REFERENCES `footwearPortal`.`user` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footwearPortal`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footwearPortal`.`program` (
  `programID` VARCHAR(8) NOT NULL,
  `companyID` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`programID`),
  INDEX `fk_program_company1_idx` (`companyID` ASC),
  CONSTRAINT `fk_program_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `footwearPortal`.`company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footwearPortal`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footwearPortal`.`employee` (
  `UID` VARCHAR(8) NOT NULL,
  `companyID` VARCHAR(8) NOT NULL,
  `programID` VARCHAR(8) NULL,
  PRIMARY KEY (`UID`, `companyID`),
  INDEX `fk_employee_company1_idx` (`companyID` ASC),
  INDEX `fk_employee_program1_idx` (`programID` ASC),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`UID`)
    REFERENCES `footwearPortal`.`user` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_company1`
    FOREIGN KEY (`companyID`)
    REFERENCES `footwearPortal`.`company` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_program1`
    FOREIGN KEY (`programID`)
    REFERENCES `footwearPortal`.`program` (`programID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footwearPortal`.`shoe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footwearPortal`.`shoe` (
  `shoeID` VARCHAR(8) NOT NULL,
  `shoeName` VARCHAR(45) NULL,
  PRIMARY KEY (`shoeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footwearPortal`.`programHasShoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footwearPortal`.`programHasShoes` (
  `programID` VARCHAR(8) NOT NULL,
  `shoeID` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`programID`, `shoeID`),
  INDEX `fk_programHasShoes_shoe1_idx` (`shoeID` ASC),
  CONSTRAINT `fk_programHasShoes_program1`
    FOREIGN KEY (`programID`)
    REFERENCES `footwearPortal`.`program` (`programID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programHasShoes_shoe1`
    FOREIGN KEY (`shoeID`)
    REFERENCES `footwearPortal`.`shoe` (`shoeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
